---
Resources:
    SingleEC2:
        Type: AWS::EC2::Instance
        Properties: 
            ImageId: "ami-0947d2ba12ee1ff75"
            KeyName: "testkey"
            AvailabilityZone: "us-east-1a"
            InstanceType: "t2.micro"
            SecurityGroupIds: 
                - !Ref InstanceSecurityGroup
            BlockDeviceMappings: 
                - DeviceName: "/dev/xvda"
                  Ebs: 
                      VolumeType: "io1"
                      Iops: "200"
                      DeleteOnTermination: "true"
                      VolumeSize: "20"
                      
                      
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: Allow ssh to client host
          SecurityGroupIngress:
              - IpProtocol: tcp
                FromPort: 22
                ToPort: 22
                CidrIp: 0.0.0.0/0